---
#Получаем дистрибутивы Vector из репозитория. Переменные (имена и версии пакетов, платформа) описываются в
#переменных для Vector (group_vars/vector/vars.yml).

- name: Modify mirrorlist in yum repos
  shell: bash -c "sed -i -e 's|mirrorlist=||#mirrorlist=|g' /etc/yum.repos.d/CentOS-*"
  changed_when: false

- name: Modify baseurl in yum repos
  shell: bash -c "sed -i -e 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*"
  changed_when: false

- name: Get vector distrib
  ansible.builtin.get_url:
    url: "{{ vector_rpm_package }}"
    dest: "./vector-{{ vector_version }}.x86_64.rpm"
    mode: 0644

#Устанавливаем Vector
- name: Install vector package
  ansible.builtin.yum:
    name: "./vector-{{ vector_version }}.x86_64.rpm"
    state: present
    enable_plugin: localinstall
    disable_gpg_check: yes
