---
#Получаем дистрибутивы Vector из репозитория. Переменные (имена и версии пакетов, платформа) описываются в
#переменных для Vector (group_vars/vector/vars.yml).

- name: Get vector distrib
  ansible.builtin.get_url:
    url: "{{ vector_deb_package }}"
    dest: "./vector-{{ vector_version }}-amd64.deb"
#Устанавливаем Vector
- name: Install vector package
  become: true
  ansible.builtin.apt:
    deb: "{{ vector_deb_package }}"
#      - "./vector-{{ vector_version }}-amd64.deb"
#- name: Install systemd
#  become: true
#  ansible.builtin.apt:
#    deb: systemd
#- name: Install systemd-sysv
#  become: true
#  ansible.builtin.apt:
#    deb: systemd-sysv