---

- name: Check OS type and run appropriate playbook
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Check OS type
      set_fact:
        os_type: "{{ ansible_facts['ansible_distribution'] }}"

    - name: Run playbook VECTOR | Install for Debian
      include_task: install_deb.yml
      when: os_type == "Debian" or os_type == "Ubuntu"
      tags:
        Run playbook VECTOR | Install for Debian/Ubuntu
    - name: Run playbook VECTOR | Install for CentOS
      include_task: install_rpm.yml
      when: os_type == "CentOS"
      tags:
        Run playbook VECTOR | Install for CentOS

    - name: VECTOR | Configure
      include_tasks: config.yml
      tags:
        - vector_configure

    - name: VECTOR | Service
      include_tasks: service.yml
      tags:
        - vector_service
