---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: Centos7
    image: docker.io/pycontribs/centos:7
    privileged: true
    pre_build_image: true

  - name: Centos8
    image: docker.io/pycontribs/centos:8
    privileged: true
    pre_build_image: true

  - name: Debian
    image: docker.io/pycontribs/debian
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
verifier:
  name: ansible
    # you might want to add your own variables here based on what provisioning
    # you are doing like:
    # image: quay.io/centos/centos:stream8
