---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  #gather_facts: false
  tasks:

  - name: Example assertion
    assert:
      that: true

  - name: Execute vector --version
    command: vector --version
    changed_when: false
    register: vector_version_rc

  - name: Output command vector --version
    debug:
      var: vector_version_rc.stdout
